name: expense_pro
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  google_fonts: ^6.2.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  drift: ^2.22.1
  drift_flutter: ^0.2.2
  sqlite3_flutter_libs: ^0.5.27
  mrx_charts: ^0.1.3
  flutter_svg: ^2.0.16
  intl: ^0.19.0
  story: ^1.1.0
  path_provider: ^2.1.5
  animated_snack_bar: ^0.4.0
  flutter_launcher_icons: ^0.14.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  drift_dev: ^2.22.1
  build_runner: ^2.4.13


flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/
    - assets/icons/categories/
    - assets/icons/bottom_nav_bar/
    - assets/images/
    - assets/images/onboarding/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_logo.png"

